#!/usr/bin/env python3
import rospy
from std_msgs.msg import String

def gimme(data) :
    """callback function as well as the publisher to '/absolute_truth' rostopic"""
    rospy.loginfo('%s ABHIYAAN', data.data)
    publisher = rospy.Publisher('/absolute_truth',String,queue_size=1)
    publisher.publish('%s')

if __name__=='__main__':
    rospy.init_node('subscribe',anonymous=True)
    rospy.loginfo('msg received')
    while not rospy.is_shutdown():
        rospy.Subscriber('/chatter',String,gimme) #subscribing and printing the message as described in gimme funtion
        rospy.spin()
    rospy.loginfo('truth recieved')
