#!/usr/bin/env python3
import rospy
from std_msgs.msg import String
if __name__=='__main__':
# starting the publisher
    rospy.init_node('publish',anonymous=True)
    rospy.loginfo('publisher has been started')

    pub = rospy.Publisher('/chatter',String,queue_size=1) # calling the publisher 'pub'
    rate = rospy.Rate(5)
    while not rospy.is_shutdown(): 
        pub.publish('NO.1 CFI TEAM')
        rate.sleep() # publishing the message at a frequncy of 5 Hz
    # ending message from the publisher node    
    rospy.loginfo('truth published')
